In [ ]:
"""
We have a list of lists:

mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]

What kind of data structure or mathematical object could this represent? Note that all the "inner" lists have the same size.

How do we access a specific element?
"""

mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]
      ]

# The variable mat represents a matrix (or a dataframe)

# To access an element:
mat[2][1]

In [ ]:
"""
Transform the list from the previous exercise:

mat = [[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]]

into a NumPy array:
mat = np.array(mat)

How do we access individual elements?
"""

import numpy as np

# Original list
mat = [
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]
]

# Convert list to NumPy array
mat_np = np.array(mat)

# Accessing individual elements: 'array[row_index, column_index]'

# Print the full array
print(mat_np)

# Example: element in row 2, column 0 (remember indexing starts at 0)
print(mat_np[2, 0])  # Output: 10

In [ ]:
"""
We have the following NumPy array:
linear_data = np.array([x for x in range(27)])

We reshape it using the .reshape() method:
reshaped_data = linear_data.reshape((3, 3, 3))

How many dimensions does the new array have?

How do we access individual elements?
"""

import numpy as np

linear_data = np.array([x for x in range(0, 27)])
reshaped_data = linear_data.reshape(3, 3, 3)

print(reshaped_data)

# How many dimensions does the new array have?
print(reshaped_data.shape)  # (3, 3, 3) → it is a 3-dimensional array

# How do we access individual elements? Here's an example (accessing respectively: matrix index 1; row 0; column 2):
print(reshaped_data[1, 0, 2])

In [ ]:
"""
Part 1:
We have a city divided into four sectors, each of which contains
a store:
We want to count how many customers are served by the different stores: let's create a
suitable data structure using a NumPy array, where the count for each store
starts at zero.
Part 2:
Let's create a loop of 100 iterations that randomly fills one of the four
quarters, thereby simulating different customers served by the various stores.
In the end, what is the count for the UR store? And the LL store?
Which stores had more than 25 customers?
Exactly how many customers did these stores have?
What is their total?
"""

import numpy as np
import random
sectors = np.array(["UL","UR","LL","RR"])
customers = np.array([0,0,0,0])

for x in range(100):
    pos = random.randint(0,3)
    customers[pos] += 1

for y in range(len(customers)):
    print(str(sectors[y]) + " : " + str(customers[y]))
    
print("\nThe store " + str(sectors[1]) + " has " + str(customers[1]) + " customers and the store " + str(sectors[2]) + " has " + str(customers[2])+ " customers.\n")

print("Store having more than 25 customers:")
total = 0
for z in range(len(sectors)): 
    if customers[z] > 25 :
        print(str(sectors[z]) +  " has " + str(customers[z]) + " customers.")
        total += customers[z]
print("The total amount of customers for stores having more than 25 customers is: " + str(total))

In [ ]:
"""
Given nine sectors and 200 iterations:

Next year, we expect the values we just obtained to be four times as high; let’s quickly simulate the results and print them out.
"""

import numpy as np
import random
sectors = np.array(["UL","UC","UR","ML","MC","MR","LL","LC","LR"])
customers = np.array([0,0,0,0,0,0,0,0,0])

for x in range(200):
    pos = random.randint(0,8)
    customers[pos] += 1

print("\nThis is the expected result for the current year:\n")
for y in range(len(customers)):
    print(str(sectors[y]) + " : " +str(customers[y]))

for z in range(len(customers)):
    customers[z] *=4

print("\nThis is the expected result for next year:\n")
for w in range(len(customers)):
    print(str(sectors[w]) + " : " +str(customers[w]))

In [ ]:
"""
We ask the user to enter a number, then we divide it by 5, and then print
the result on the screen.

Handle exceptions correctly in case the user enters invalid input.
"""

while True:
    try:
        number = int(input("Enter an integer N to start the calculation: "))
        print("If we divide this number by 5, we get:", number / 5)
        break
    except ValueError:
        print("Hey, careful! You did not enter an integer number, please try again.")

In [ ]:
"""
In an assembly line, we have a metal structure that is 28.75 cm long.
To ensure its stability, it is necessary to insert 15 rivets, including
one at the beginning and one at the end, all equally spaced.
How can we calculate the exact positions where the rivets should be placed using NumPy?
"""

import numpy as np

structure_length = 28.75
num_rivets = 15

distance = structure_length / (num_rivets - 1)

positions = np.array([distance * x for x in range(num_rivets)])

print("Place the rivets along the structure at the following positions (measured in cm):\n")

for pos in positions:
    print(round(pos, 2))


# Alternative solution

import numpy as np

structure_length = 28.75
num_rivets = 15

exact_positions = np.linspace(0, structure_length, num=num_rivets)

print("\nPlace the rivets along the structure at the following positions (measured in cm):\n")

for pos in exact_positions:
    print(round(pos, 2))

In [ ]:
"""
Consider the following dictionary:
revenue_dict = {
    1997: 12_000,
    1998: 15_000,
    1999: 20_000,
    2000: 23_000,
    2001: 25_000,
    2002: 17_000,
    2003: 14_000,
    2004: 21_000
}

Now consider the following Series:
revenue_series = pd.Series(
    [12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
    index=range(1997, 2005)
)

We can access the same information in the same way:
revenue_dict[1997]
revenue_series[1997]

So, what is the difference between the two data types?
What can we do with a Series that we cannot do with a dictionary?
"""

revenue_dict = {
    1997: 12_000,
    1998: 15_000,
    1999: 20_000,
    2000: 23_000,
    2001: 25_000,
    2002: 17_000,
    2003: 14_000,
    2004: 21_000
}

revenue_series = pd.Series(
    [12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
    index=range(1997, 2005)
)

# Compared to a dictionary, Pandas Series allow access to elements both through positional indexes and custom indexes.

# In addition, Series natively support vectorized operations and provide many useful features for data analysis.

In [ ]:
"""
Given the following matrix:

[[1, 1, 1, 1],
 [5, 1, 1, 1],
 [20, -4, 0, 42]]

Let's create an ndarray with the same values.

There are two ways to do this: initialize an array and then insert the values
into the appropriate positions, or create a list of lists and then cast it.
"""

import numpy as np

values = [1, 1, 1, 1, 5, 1, 1, 1, 20, -4, 0, 42]
array = np.array(values)
array = array.reshape(3, 4)

print("Array contents:\n", array)

# Alternative solution 1:
import numpy as np

array = np.array([1, 1, 1, 1, 5, 1, 1, 1, 20, -4, 0, 42])
array = array.reshape(3, 4)

print("Array contents:\n", array)

# Alternative solution 2:
import numpy as np

array = np.array([
    [1, 1, 1, 1],
    [5, 1, 1, 1],
    [20, -4, 0, 42]
])

print("Array contents:\n", array)

In [ ]:
"""
Create the following 5 x 5 ndarray:
[[10 22 21  8  9]
 [ 9 42  3 18 11]
 [ 5  4 30 12 29]
 [37 31  7  2 26]
 [ 8  6  4 33 15]]

For each value, subtract the minimum value (2) and then divide the result by
the maximum value (42) minus the minimum value.
"""

import numpy as np

matrix = np.array([[10, 22, 21, 8, 9],
                   [9, 42, 3, 18, 11],
                   [5, 4, 30, 12, 29],
                   [37, 31, 7, 2, 26],
                   [8, 6, 4, 33, 15]])

print("The content of the original matrix is:\n\n", matrix, "\n")

min_val = np.min(matrix)
print("The minimum value in the original matrix is:", min_val, "\n")

max_val = np.max(matrix)
print("The maximum value in the original matrix is:", max_val, "\n")

result_matrix = (matrix - min_val) / (max_val - min_val)

print("The content of the resulting matrix is:\n\n", result_matrix)