In [ ]:
"""
1.
Abbiamo una lista di liste:

mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

Che tipo di struttura dati o matematica potrebbe rappresentare? Notare che
tutte le liste "interne" sono della stessa dimensione

Come facciamo per accedere ad un elemento in particolare?
"""

mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]
      ]

# La variabile mat rappresenta una matrice, o un dataframe
# Per richiamare un elemento:
mat[2][1]

In [ ]:
"""
2.
Trasformiamo la lista dell'esercizio precedente
mat = [[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]]

in un array NumPy:
mat = np.array(mat)

Come facciamo per accedere ai singoli elementi?
"""

import numpy as np
mat = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]
mat_ny = np.array(mat)

# Per accedere ai singoli elementi:
print(mat_ny)
print(mat_ny[2,0])

In [ ]:
"""
3.
Abbiamo il seguente array NumPy:
linear_data = np.array([x for x in range(27)])
Lo ridimensioniamo mediante il metodo .reshape():
reshaped_data = linear_data.reshape((3, 3, 3))

Quante dimensioni ha il nuovo array?

Come facciamo per accedere ai singoli elementi?
"""

import numpy as np
linear_data = np.array([x for x in range(0,27)])
reshaped_data = linear_data.reshape(3,3,3)

print(reshaped_data)

# Quante dimensioni ha il nuovo array?
print(reshaped_data.shape)

# Come facciamo per accedere ai singoli elementi?
print(reshaped_data[1,0,2]) # Per accedere rispettivamente a: matrice 1, riga 0, colonna 2

In [ ]:
"""
4. Parte 1
Abbiamo un territorio cittadino diviso in quattro quadranti; in ognuno di essi c'è
uno store:
Vogliamo contare quanti clienti vengono serviti dai diversi store: creiamo una
struttura dati adeguata con un array NumPy, dove il conteggio di ogni store
parta da zero.
   Parte 2
Creiamo un ciclo di 100 iterazioni che riempia, a caso, uno dei quattro
quadranti, simulando quindi diversi clienti serviti dai vari store.
Alla fine, che valore ha lo store UR? E lo store LL?
Quali store hanno avuto più di 25 clienti?
Quanti clienti hanno avuto di preciso questi store?
Qual è la loro somma?
"""

import numpy as np
import random
quadranti = np.array(["UL","UR","LL","RR"])
clienti = np.array([0,0,0,0])

for x in range(100):
    pos = random.randint(0,3)
    clienti[pos] += 1

for y in range(len(clienti)):
    print(str(quadranti[y]) + " : " + str(clienti[y]))
    
print("\nLo store " + str(quadranti[1]) + " ha " + str(clienti[1]) + " clienti e lo store " + str(quadranti[2]) + " ha " + str(clienti[2])+ " clienti.")

print("Store con più di 25 clienti:")
somma = 0
for z in range(len(quadranti)): 
    if clienti[z] > 25 :
        print(str(quadranti[z]) +  " ha " + str(clienti[z]) + " clienti.")
        somma += clienti[z]
print("La somma dei clienti è: " + str(somma))

In [ ]:
"""
4. Parte 3
Ripetiamo la traccia precedente, ma stavolta abbiamo nove quadranti e 200
iterazioni:

L'anno prossimo ci aspettiamo 4 volte tanto i valori appena ottenuti; simuliamo
velocemente il tutto e stampiamo il risultato.
"""

import numpy as np
import random
quadranti = np.array(["UL","UC","UR","ML","MC","MR","LL","LC","LR"])
clienti = np.array([0,0,0,0,0,0,0,0,0])

for x in range(200):
    pos = random.randint(0,8)
    clienti[pos] += 1

print("\nPer questo anno la situazione è la seguente:")
for y in range(len(clienti)):
    print(str(quadranti[y]) + " : " +str(clienti[y]))

for z in range(len(clienti)):
    clienti[z] *=4

print("\nPer il prossimo anno la situazione attesa è la seguente:")
for w in range(len(clienti)):
    print(str(quadranti[w]) + " : " +str(clienti[w]))

In [ ]:
"""
5.
Chiediamo all'utente di inserire un numero, dividiamolo per 5 e poi stampiamo
il risultato a video.

Gestiamo correttamente le eccezioni nel caso l'utente immetta un input errato.
"""

while True:
    try:
        numero = int(input("Inserisci un numero intero N per avviare il calcolo:"))
        print("Se dividiamo questo numero per 5, otteniamo:", numero/5)
        break
    except:
        print("Hey, attenzione! Non hai inserito un numero intero, riprova.")

In [ ]:
"""
6.
In una catena di montaggio abbiamo una struttura metallica di 28.75 cm di
lunghezza; per assicurarne la stabilità, è necessario inserire 15 rivetti, dei quali
uno all'inizio e uno alla fine, e tutti quanti separati dalla stessa distanza; come
possiamo calcolare i punti esatti in cui inserire i rivetti tramite NumPy?
"""

import numpy as np
lungh_strutt = 28.75
num_rivetti = 15
dist = lungh_strutt/(num_rivetti-1)
array = np.array([dist * x for x in range(num_rivetti)])

print("Posizionare i rivetti lungo la struttura nei seguenti punti (misura in cm):\n")
for y in array:
    print(round((y),2))

# Soluzione alternativa

import numpy as np
lungh_strutt = 28.75
num_rivetti = 15
punti_esatti = np.linspace(0,lungh_strutt,num = num_rivetti)

print("Posizionare i rivetti lungo la struttura nei seguenti punti (misura in cm):\n")
for x in punti_esatti:
    print(round((x),2))

In [ ]:
"""
7.1
Scarichiamo l'Iris dataset da qui: https://archive.ics.uci.edu/dataset/53/iris
Troveremo un file .data, che è un CSV, e un file .names con i metadati; questa
versione del dataset non ha i nomi di colonna.
• Leggiamo il file e carichiamolo in un DataFrame mediante pd.read_csv()
senza utilizzare altri parametri
• Stampiamo le prime cinque righe
• Stampiamo i nomi di colonna: sono corretti?
7.2
Dal dataset di prima:
• Leggiamo il file e carichiamolo in un DataFrame, aggiungendo i nomi di
colonna — che si trovano nel file .names — come parametro di
pd.read_csv()
• Stampiamo le prime cinque righe e le ultime dieci
• Stampiamo un riepilogo dei descrittori statistici del dataset
"""

import pandas as pd
data_set = pd.read_csv("iris.data")

# Stampiamo le prime 5 righe
print(data_set.head())

# Stampiamo i nomi di colonna: sono corretti?
print(data_set.columns) # Allo stato attuale, i nomi delle colonne non sono corretti

# Leggiamo il file e carichiamolo in un DataFrame, aggiungendo i nomi di colonna — che si trovano nel file .names — come parametro di pd.read_csv()
data_set = pd.read_csv("iris.data",header=None,names=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','class'])

#Stampiamo le prime cinque righe
data_set.head() # Per default vengono stampate le prime cinque righe utilizzando .head()

#Stampiamo le ultime dieci righe
data_set.tail(10)

# Stampiamo un riepilogo dei descrittori statistici del dataset
data_set.describe()

In [ ]:
"""
8.
Andiamo a questo link e scarichiamo una serie di dataset:
https://www.kaggle.com/datasets/ahmettezcantekin/beginner-datasets

Tra i vari dataset presenti, ce n'è uno che contiene diverse qualità di vini e le
misure di diverse proprietà organolettiche, wine.csv;
Leggiamo quindi il dataset wine.csv, e visualizziamone le prime e le ultime
righe;
Leggiamo nuovamente il dataset, ma stavolta considerando soltanto le ultime 6
colonne, ricordandoci che in totale il dataset ha 13 colonne;
Visualizziamo un resoconto dei descrittori statistici di questa versione.
"""

import pandas as pd
wine = pd.read_csv("wine.csv")
wine.head()
wine.tail()

# Leggiamo nuovamente il dataset ma stavolta considerando solo le ultime 6 colonne ricordandoci che in totale il dataset ha 13 colonne
wine = pd.read_csv("wine.csv", usecols=[x for x in range(7,13,1)])
wine

# Visualizziamo un resoconto dei descrittori statistici di questa versione
wine.describe()

In [ ]:
"""
9.
Consideriamo il seguente dizionario:
fatturati_dict = {1997: 12_000, 1998: 15_000,
1999: 20_000, 2000: 23_000, 2001: 25_000,
2002: 17_000, 2003: 14_000, 2004: 21_000}

Consideriamo ora la seguente Series:
fatturati_series = pd.Series([12_000, 15_000, 20_000,
23_000, 25_000, 17_000, 14_000, 21_000],
index=range(1997, 2005))

Possiamo accedere alle stesse informazioni nello stesso modo:
fatturati_dict[1997]
fatturati_series[1997]
Dunque qual è la differenza tra i due tipi di dato?
Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
"""

fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000 ,2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

# Rispetto ad un dizionario, le Series di Pandas consentono l'accesso agli elementi sia con indici posizionali che con indici personalizzati
# # Inoltre, le Series supportano operazioni vettoriali in modo nativo e offrono diverse funzionalità utili in ambito Data Analysis

In [ ]:
"""
10.
Abbiamo la seguente matrice:

[[1,1,1,1],
 [5,1,1,1],
 [20,-4,0,42]]

Creiamo un ndarray con gli stessi valori.

Ci sono due modalità: inizializzare un array e poi inserire i valori nelle posizioni
adatte, oppure creare una lista di liste e poi effettuare un casting.
"""

import numpy as np
list = [1,1,1,1,5,1,1,1,20,-4,0,42]
array = np.array(list)
array = array.reshape(3,4)
print("Contenuto dell'array:\n", array)

# Soluzione alternativa 1:
import numpy as np
array = np.array([1,1,1,1,5,1,1,1,20,-4,0,42])
array = array.reshape(3,4) 
print("Contenuto dell'array:\n", array)

# Soluzione alternativa 2:
import numpy as np
array = np.array([[1, 1, 1, 1], [5, 1, 1, 1], [20, -4, 0, 42]])
print("Contenuto dell'array:\n", array)

In [ ]:
"""
11.
Creiamo il seguente ndarray 5 x 5:
[[10 22 21  8  9]
 [ 9 42  3 18 11]
 [ 5  4 30 12 29]
 [37 31  7  2 26]
 [ 8  6  4 33 15]]
Per ogni valore, sottraiamo il minimo (2) e poi dividiamo il risultato per il
massimo (42) meno il minimo.
"""

import numpy as np
matrix = np.array([[10, 22, 21, 8, 9],
                   [9, 42, 3, 18, 11],
                   [5, 4, 30, 12, 29],
                   [37, 31, 7, 2, 26],
                   [8, 6, 4, 33, 15]])
print("Il contenuto della matrice di partenza è:\n\n", matrix,"\n")

min_val = np.min(matrix)
print("Il valore minimo nella matrice di partenza è:", min_val,"\n")

max_val = np.max(matrix)
print("Il valore massimo nella matrice di partenza è:", max_val,"\n")

result_matrix = (matrix - min_val) / (max_val - min_val)
print("Il contenuto della matrice risultante è:\n\n", result_matrix)